version: 2.1

orbs:
  clair_scanner: ovotech/clair-scanner@dev:failParameter

jobs:
  scan_images_ignore_fail:
    executor: clair_scanner/default
    steps:
    - clair_scanner/scan:
        image: debian:wheezy
        fail_on_discovered_vulnerabilities: false

  scan_images:
    executor: clair_scanner/default
    steps:
    - clair_scanner/scan:
        image: debian:wheezy

workflows:
  test:
    jobs:
      - scan_images
      - scan_images_ignore_fail
